nodeLinker: node-modules        # avoid PnP surprises; matches current repo
enableGlobalCache: true         # faster CI (shared global cache)
checksumBehavior: throw         # fail if lockfile checksums don't match
npmPublishAccess: public