nodeLinker: node-modules
enableGlobalCache: true
checksumBehavior: throw
npmPublishAccess: public
npmRegistryServer: "https://registry.npmjs.org"
httpRetry: 8
httpTimeout: 180000
networkConcurrency: 1
