// Re-export lucide-react icons with consistent naming
export {
  Play,
  Pause,
  ChevronRight,
  ChevronDown,
  Tag as TagIcon,
  Music,
  Download,
  Loader2 as Spinner,
  Volume2 as Volume,
  VolumeX as VolumeMute,
  VolumeX,
  SkipBack,
  SkipForward,
  Check,
  CheckCircle,
  CreditCard,
  Lock,
  ShoppingCart,
  X,
  XCircle,
  ArrowRight,
  Star,
  Wallet,
  ExternalLink,
  Upload,
  AlertCircle,
  AlertTriangle,
  File,
  Clock,
  Info,
  Archive,
  Copy,
  Edit,
  Globe,
  MoreHorizontal,
  MoreVertical,
  Trash2,
  Archive as Unarchive,
  Save,
  Heart,
  Share2,
} from "lucide-react";

// Placeholder exports for custom SVGR icons (to be implemented)
// These will be replaced with actual SVG components later
export { Play as Wave } from "lucide-react";
export { Activity as Bpm } from "lucide-react";
export { Music2 as KeySig } from "lucide-react";
