import { generateIdAtTime } from "@/lib/ulid";
import { db, schema } from "./index";
import { sql, eq } from "drizzle-orm";

// Fixed timestamps for deterministic seeding (CI/E2E stability)
const BASE_TIMESTAMP = new Date("2025-01-01T00:00:00Z");
const HOUR_MS = 60 * 60 * 1000;

// Parameterize owner ID for E2E tests
const OWNER_ID = process.env.E2E_OWNER_ID ?? "mock-producer-123";

// Clean seed data with only our 24 new assets
const ASSETS = [
  {
    id: "asset-new-001",
    title: "Analog 808 Drum Machine Close Up Glowing Red Pads",
    artist: "Rules",
    bpm: 121,
    key: "F minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-001.mp3",
    coverUrl: "/media/covers/asset-new-001-3000.jpg",
    heroUrl: "/media/heroes/asset-new-001-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-001-512.jpg",
    waveUrl: "/media/waveforms/asset-new-001-wave-1024x256.png",
    price: { currency: "USD", amount: 3 },
    priceCredits: 4,
    duration: 180,
    fileSize: 25000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime()),
    updatedAt: new Date(BASE_TIMESTAMP.getTime()),
    status: "published",
    genre: "Drum & Bass",
    assetType: "sample",
    tags: ["drum & bass", "sample", "new"],
    isNew: true,
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: "asset-new-002",
    title: "Classical String Section — Cello And Violin Under Soft Light",
    artist: "Rules",
    bpm: 95,
    key: "G major",
    previewUrl: "https://cdn.example.com/previews/asset-new-002.mp3",
    coverUrl: "/media/covers/asset-new-002-3000.jpg",
    heroUrl: "/media/heroes/asset-new-002-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-002-512.jpg",
    waveUrl: "/media/waveforms/asset-new-002-wave-1024x256.png",
    price: { currency: "USD", amount: 8 },
    priceCredits: 10,
    duration: 240,
    fileSize: 30000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + HOUR_MS),
    status: "published",
    genre: "Classical",
    assetType: "sample",
    tags: ["classical", "sample", "new"],
    isNew: true,
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: "asset-new-003",
    title: "Close Up Vinyl Record Under Warm Light, Dust Visible",
    artist: "Rules",
    bpm: 110,
    key: "A minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-003.mp3",
    coverUrl: "/media/covers/asset-new-003-3000.jpg",
    heroUrl: "/media/heroes/asset-new-003-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-003-512.jpg",
    waveUrl: "/media/waveforms/asset-new-003-wave-1024x256.png",
    price: { currency: "USD", amount: 13 },
    priceCredits: 16,
    duration: 195,
    fileSize: 28000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 2 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 2 * HOUR_MS),
    status: "published",
    genre: "Electronic",
    assetType: "sample",
    tags: ["electronic", "sample", "new"],
    isNew: true,
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: "asset-new-004",
    title: "Congas, Djembes, And Shakers In Warm Sunset Tones",
    artist: "Rules",
    bpm: 105,
    key: "D major",
    previewUrl: "https://cdn.example.com/previews/asset-new-004.mp3",
    coverUrl: "/media/covers/asset-new-004-3000.jpg",
    heroUrl: "/media/heroes/asset-new-004-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-004-512.jpg",
    waveUrl: "/media/waveforms/asset-new-004-wave-1024x256.png",
    price: { currency: "USD", amount: 8 },
    priceCredits: 10,
    duration: 165,
    fileSize: 22000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 3 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 3 * HOUR_MS),
    status: "published",
    genre: "Electronic",
    assetType: "sample",
    tags: ["electronic", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-005",
    title: "Dream Pop Duo Sitting On Retro Couch With Vintage Lighting",
    artist: "Rules",
    bpm: 85,
    key: "E minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-005.mp3",
    coverUrl: "/media/covers/asset-new-005-3000.jpg",
    heroUrl: "/media/heroes/asset-new-005-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-005-512.jpg",
    waveUrl: "/media/waveforms/asset-new-005-wave-1024x256.png",
    price: { currency: "USD", amount: 15 },
    priceCredits: 18,
    duration: 210,
    fileSize: 32000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 4 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 4 * HOUR_MS),
    status: "published",
    genre: "Synthwave",
    assetType: "sample",
    tags: ["synthwave", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-006",
    title: "Electric Guitar Neck Under Studio Lights, Reflective Chrome Tones",
    artist: "Rules",
    bpm: 140,
    key: "B minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-006.mp3",
    coverUrl: "/media/covers/asset-new-006-3000.jpg",
    heroUrl: "/media/heroes/asset-new-006-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-006-512.jpg",
    waveUrl: "/media/waveforms/asset-new-006-wave-1024x256.png",
    price: { currency: "USD", amount: 2 },
    priceCredits: 3,
    duration: 150,
    fileSize: 18000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 5 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 5 * HOUR_MS),
    status: "published",
    genre: "Rock",
    assetType: "sample",
    tags: ["rock", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-007",
    title: "Lo Fi Electric Piano Keyboard On A Wooden Desk With Vinyl And Lamp",
    artist: "Rules",
    bpm: 75,
    key: "C major",
    previewUrl: "https://cdn.example.com/previews/asset-new-007.mp3",
    coverUrl: "/media/covers/asset-new-007-3000.jpg",
    heroUrl: "/media/heroes/asset-new-007-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-007-512.jpg",
    waveUrl: "/media/waveforms/asset-new-007-wave-1024x256.png",
    price: { currency: "USD", amount: 3 },
    priceCredits: 4,
    duration: 120,
    fileSize: 15000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 6 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 6 * HOUR_MS),
    status: "published",
    genre: "Piano",
    assetType: "sample",
    tags: ["piano", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-008",
    title: "Mpc Sampler On Desk With Coffee And Vinyl Crate",
    artist: "Rules",
    bpm: 125,
    key: "F# minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-008.mp3",
    coverUrl: "/media/covers/asset-new-008-3000.jpg",
    heroUrl: "/media/heroes/asset-new-008-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-008-512.jpg",
    waveUrl: "/media/waveforms/asset-new-008-wave-1024x256.png",
    price: { currency: "USD", amount: 4 },
    priceCredits: 5,
    duration: 180,
    fileSize: 25000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 7 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 7 * HOUR_MS),
    status: "published",
    genre: "Electronic",
    assetType: "sample",
    tags: ["electronic", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-009",
    title: "Modular Synth Cables Glowing In Ambient Purple Light",
    artist: "Rules",
    bpm: 130,
    key: "G# minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-009.mp3",
    coverUrl: "/media/covers/asset-new-009-3000.jpg",
    heroUrl: "/media/heroes/asset-new-009-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-009-512.jpg",
    waveUrl: "/media/waveforms/asset-new-009-wave-1024x256.png",
    price: { currency: "USD", amount: 9 },
    priceCredits: 11,
    duration: 200,
    fileSize: 30000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 8 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 8 * HOUR_MS),
    status: "published",
    genre: "Techno",
    assetType: "sample",
    tags: ["techno", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-010",
    title: "Studio Microphone Glowing Under Neon Pink And Blue Light",
    artist: "Rules",
    bpm: 95,
    key: "A# major",
    previewUrl: "https://cdn.example.com/previews/asset-new-010.mp3",
    coverUrl: "/media/covers/asset-new-010-3000.jpg",
    heroUrl: "/media/heroes/asset-new-010-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-010-512.jpg",
    waveUrl: "/media/waveforms/asset-new-010-wave-1024x256.png",
    price: { currency: "USD", amount: 4 },
    priceCredits: 5,
    duration: 175,
    fileSize: 22000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 9 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 9 * HOUR_MS),
    status: "published",
    genre: "Trap",
    assetType: "sample",
    tags: ["trap", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-011",
    title: "Trumpet And Saxophones Under Stage Lights",
    artist: "Rules",
    bpm: 115,
    key: "D major",
    previewUrl: "https://cdn.example.com/previews/asset-new-011.mp3",
    coverUrl: "/media/covers/asset-new-011-3000.jpg",
    heroUrl: "/media/heroes/asset-new-011-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-011-512.jpg",
    waveUrl: "/media/waveforms/asset-new-011-wave-1024x256.png",
    price: { currency: "USD", amount: 13 },
    priceCredits: 16,
    duration: 190,
    fileSize: 28000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 10 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 10 * HOUR_MS),
    status: "published",
    genre: "Jazz",
    assetType: "sample",
    tags: ["jazz", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-012",
    title: "Vintage Drum Set In Cozy Studio Corner",
    artist: "Rules",
    bpm: 120,
    key: "E minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-012.mp3",
    coverUrl: "/media/covers/asset-new-012-3000.jpg",
    heroUrl: "/media/heroes/asset-new-012-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-012-512.jpg",
    waveUrl: "/media/waveforms/asset-new-012-wave-1024x256.png",
    price: { currency: "USD", amount: 4 },
    priceCredits: 5,
    duration: 160,
    fileSize: 20000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 11 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 11 * HOUR_MS),
    status: "published",
    genre: "Drum & Bass",
    assetType: "sample",
    tags: ["drum & bass", "sample", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-013",
    title: "Neon Night Drive — Retro Synthwave Aesthetic With Glowing City Lights",
    artist: "GotMusic Producer",
    bpm: 129,
    key: "C# minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-013.mp3",
    coverUrl: "/media/covers/asset-new-013-3000.jpg",
    heroUrl: "/media/heroes/asset-new-013-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-013-512.jpg",
    waveUrl: "/media/waveforms/asset-new-013-wave-1024x256.png",
    price: { currency: "USD", amount: 8 },
    priceCredits: 10,
    duration: 220,
    fileSize: 35000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 12 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 12 * HOUR_MS),
    status: "published",
    genre: "Techno",
    assetType: "track",
    tags: ["techno", "track", "new"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
  },
  {
    id: "asset-new-014",
    title: "1970s Funk Revival With Bright Colors, Grainy Texture",
    artist: "GotMusic Producer",
    bpm: 106,
    key: "D major",
    previewUrl: "https://cdn.example.com/previews/asset-new-014.mp3",
    coverUrl: "/media/covers/asset-new-014-3000.jpg",
    heroUrl: "/media/heroes/asset-new-014-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-014-512.jpg",
    waveUrl: "/media/waveforms/asset-new-014-wave-1024x256.png",
    price: { currency: "USD", amount: 13 },
    priceCredits: 16,
    duration: 250,
    fileSize: 40000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 13 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 13 * HOUR_MS),
    status: "published",
    genre: "Funk/Soul",
    assetType: "track",
    tags: ["funk/soul", "track", "new"],
    isNew: true,
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: "asset-new-015",
    title: "Ambient Soundscape — Foggy Mountains Or Misty Forest Minimalism",
    artist: "Rules",
    bpm: 75,
    key: "D# major",
    previewUrl: "https://cdn.example.com/previews/asset-new-015.mp3",
    coverUrl: "/media/covers/asset-new-015-3000.jpg",
    heroUrl: "/media/heroes/asset-new-015-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-015-512.jpg",
    waveUrl: "/media/waveforms/asset-new-015-wave-1024x256.png",
    price: { currency: "USD", amount: 12 },
    priceCredits: 14,
    duration: 300,
    fileSize: 45000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 14 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 14 * HOUR_MS),
    status: "published",
    genre: "Ambient",
    assetType: "track",
    tags: ["ambient", "track", "new"],
    isNew: true,
    isFeatured: true,
    isExclusive: false,
  },
  {
    id: "asset-new-016",
    title: "Country Singer Leaning On Pickup Truck At Dusk",
    artist: "Rules",
    bpm: 84,
    key: "A# minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-016.mp3",
    coverUrl: "/media/covers/asset-new-016-3000.jpg",
    heroUrl: "/media/heroes/asset-new-016-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-016-512.jpg",
    waveUrl: "/media/waveforms/asset-new-016-wave-1024x256.png",
    price: { currency: "USD", amount: 9 },
    priceCredits: 11,
    duration: 180,
    fileSize: 28000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 15 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 15 * HOUR_MS),
    status: "published",
    genre: "Country",
    assetType: "track",
    tags: ["country", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-017",
    title: "Ethereal Forest Singer Portrait With Natural Green Light",
    artist: "GotMusic Producer",
    bpm: 76,
    key: "F major",
    previewUrl: "https://cdn.example.com/previews/asset-new-017.mp3",
    coverUrl: "/media/covers/asset-new-017-3000.jpg",
    heroUrl: "/media/heroes/asset-new-017-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-017-512.jpg",
    waveUrl: "/media/waveforms/asset-new-017-wave-1024x256.png",
    price: { currency: "USD", amount: 9 },
    priceCredits: 11,
    duration: 200,
    fileSize: 32000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 16 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 16 * HOUR_MS),
    status: "published",
    genre: "Ambient",
    assetType: "track",
    tags: ["ambient", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-018",
    title: "Indie Folk Duo In A Sunset Field With Acoustic Guitar",
    artist: "Rules",
    bpm: 90,
    key: "D# minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-018.mp3",
    coverUrl: "/media/covers/asset-new-018-3000.jpg",
    heroUrl: "/media/heroes/asset-new-018-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-018-512.jpg",
    waveUrl: "/media/waveforms/asset-new-018-wave-1024x256.png",
    price: { currency: "USD", amount: 3 },
    priceCredits: 4,
    duration: 170,
    fileSize: 25000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 17 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 17 * HOUR_MS),
    status: "published",
    genre: "Folk",
    assetType: "track",
    tags: ["folk", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-019",
    title: "Jazz Trio Performing Live On Dim Stage, Soft Spotlight",
    artist: "GotMusic Producer",
    bpm: 113,
    key: "A minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-019.mp3",
    coverUrl: "/media/covers/asset-new-019-3000.jpg",
    heroUrl: "/media/heroes/asset-new-019-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-019-512.jpg",
    waveUrl: "/media/waveforms/asset-new-019-wave-1024x256.png",
    price: { currency: "USD", amount: 8 },
    priceCredits: 10,
    duration: 240,
    fileSize: 38000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 18 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 18 * HOUR_MS),
    status: "published",
    genre: "Jazz",
    assetType: "track",
    tags: ["jazz", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-020",
    title: "Minimal Techno — Grayscale Texture With Subtle Motion Blur",
    artist: "GotMusic Producer",
    bpm: 125,
    key: "D minor",
    previewUrl: "https://cdn.example.com/previews/asset-new-020.mp3",
    coverUrl: "/media/covers/asset-new-020-3000.jpg",
    heroUrl: "/media/heroes/asset-new-020-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-020-512.jpg",
    waveUrl: "/media/waveforms/asset-new-020-wave-1024x256.png",
    price: { currency: "USD", amount: 8 },
    priceCredits: 10,
    duration: 190,
    fileSize: 30000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 19 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 19 * HOUR_MS),
    status: "published",
    genre: "Techno",
    assetType: "track",
    tags: ["techno", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-021",
    title: "Punk Style Portrait With Ripped Text Look And Grain",
    artist: "GotMusic Producer",
    bpm: 154,
    key: "D major",
    previewUrl: "https://cdn.example.com/previews/asset-new-021.mp3",
    coverUrl: "/media/covers/asset-new-021-3000.jpg",
    heroUrl: "/media/heroes/asset-new-021-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-021-512.jpg",
    waveUrl: "/media/waveforms/asset-new-021-wave-1024x256.png",
    price: { currency: "USD", amount: 12 },
    priceCredits: 14,
    duration: 160,
    fileSize: 25000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 20 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 20 * HOUR_MS),
    status: "published",
    genre: "Punk",
    assetType: "track",
    tags: ["punk", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-022",
    title: "Rapper On City Rooftop At Dusk With Skyline Backdrop",
    artist: "GotMusic Producer",
    bpm: 81,
    key: "F# major",
    previewUrl: "https://cdn.example.com/previews/asset-new-022.mp3",
    coverUrl: "/media/covers/asset-new-022-3000.jpg",
    heroUrl: "/media/heroes/asset-new-022-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-022-512.jpg",
    waveUrl: "/media/waveforms/asset-new-022-wave-1024x256.png",
    price: { currency: "USD", amount: 15 },
    priceCredits: 18,
    duration: 220,
    fileSize: 35000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 21 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 21 * HOUR_MS),
    status: "published",
    genre: "Hip-Hop",
    assetType: "track",
    tags: ["hip-hop", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-023",
    title: "Soul Singer Portrait With Warm Golden Backlight",
    artist: "Rules",
    bpm: 104,
    key: "E major",
    previewUrl: "https://cdn.example.com/previews/asset-new-023.mp3",
    coverUrl: "/media/covers/asset-new-023-3000.jpg",
    heroUrl: "/media/heroes/asset-new-023-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-023-512.jpg",
    waveUrl: "/media/waveforms/asset-new-023-wave-1024x256.png",
    price: { currency: "USD", amount: 12 },
    priceCredits: 14,
    duration: 200,
    fileSize: 32000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 22 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 22 * HOUR_MS),
    status: "published",
    genre: "Funk/Soul",
    assetType: "track",
    tags: ["funk/soul", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
  {
    id: "asset-new-024",
    title: "Trap Producer In Smoky Studio, Neon Red Lighting",
    artist: "Rules",
    bpm: 84,
    key: "E major",
    previewUrl: "https://cdn.example.com/previews/asset-new-024.mp3",
    coverUrl: "/media/covers/asset-new-024-3000.jpg",
    heroUrl: "/media/heroes/asset-new-024-1024.jpg",
    thumbUrl: "/media/thumbnails/asset-new-024-512.jpg",
    waveUrl: "/media/waveforms/asset-new-024-wave-1024x256.png",
    price: { currency: "USD", amount: 15 },
    priceCredits: 18,
    duration: 180,
    fileSize: 28000000,
    ownerId: OWNER_ID,
    createdAt: new Date(BASE_TIMESTAMP.getTime() + 23 * HOUR_MS),
    updatedAt: new Date(BASE_TIMESTAMP.getTime() + 23 * HOUR_MS),
    status: "published",
    genre: "Hip-Hop",
    assetType: "track",
    tags: ["hip-hop", "track", "new"],
    isNew: true,
    isFeatured: false,
    isExclusive: false,
  },
];

export async function seed() {
  console.log("🌱 Seeding database with 24 new assets...");

  try {
    // Clear existing assets
    await db.delete(schema.assets);
    console.log("🗑️ Cleared existing assets");

    // Insert new assets
    for (const asset of ASSETS) {
      await db.insert(schema.assets).values({
        id: asset.id,
        title: asset.title,
        artist: asset.artist,
        bpm: asset.bpm,
        keySig: asset.key,
        priceAmount: asset.price.amount,
        priceCurrency: asset.price.currency,
        status: asset.status,
        ownerId: asset.ownerId,
        createdAt: asset.createdAt,
        updatedAt: asset.updatedAt,
        // Add asset type for CTA system
        assetType: asset.assetType,
        isNew: asset.isNew,
        isFeatured: asset.isFeatured,
        isExclusive: asset.isExclusive,
        genre: asset.genre,
        tags: JSON.stringify(asset.tags),
      });
    }

    console.log(`✅ Seeded ${ASSETS.length} assets successfully`);
    console.log(`📊 Summary:`);
    console.log(`  - Samples: ${ASSETS.filter(a => a.assetType === 'sample').length}`);
    console.log(`  - Tracks: ${ASSETS.filter(a => a.assetType === 'track').length}`);
    console.log(`  - Genres: ${[...new Set(ASSETS.map(a => a.genre))].length} unique`);
    console.log(`  - Price Range: $${Math.min(...ASSETS.map(a => a.price.amount))} - $${Math.max(...ASSETS.map(a => a.price.amount))}`);

  } catch (error) {
    console.error("❌ Seeding failed:", error);
    throw error;
  }
}

if (require.main === module) {
  seed().catch(console.error);
}