name: Project Auto-Add
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PROJECT_URL is set
        id: check
        run: |
          if [ -z "${{ vars.PROJECT_URL }}" ]; then
            echo "PROJECT_URL not set, skipping project auto-add"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Add to project
        if: steps.check.outputs.skip != 'true'
        uses: actions/add-to-project@v0.6.0
        with:
          # Set PROJECT_URL as a repository variable in Settings → Secrets and variables → Actions → Variables
          # Format: https://github.com/orgs/GotMusic/projects/NUMBER
          # Or: https://github.com/users/grantedwards/projects/NUMBER
          project-url: ${{ vars.PROJECT_URL }}
          # Use PROJECT_TOKEN secret for user projects (requires fine-grained PAT with project:write permission)
          # Fallback to GITHUB_TOKEN for org projects
          github-token: ${{ secrets.PROJECT_TOKEN || secrets.GITHUB_TOKEN }}

