name: Project Auto-Add
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  add:
    # Skip if PROJECT_URL secret is not set
    if: vars.PROJECT_URL != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.0
        with:
          # Set PROJECT_URL as a repository variable in Settings → Secrets and variables → Actions → Variables
          # Format: https://github.com/orgs/GotMusic/projects/NUMBER
          # Or: https://github.com/users/grantedwards/projects/NUMBER
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

