name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check for override label
        if: github.event_name == 'pull_request'
        id: check-override
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const hasOverride = labels.includes('override:hygiene');
            console.log('PR labels:', labels);
            console.log('Has override:hygiene:', hasOverride);
            core.setOutput('skip', hasOverride ? 'true' : 'false');
      
      - name: Checkout code
        if: steps.check-override.outputs.skip != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks to scan all commits
      
      - name: Run Gitleaks
        if: steps.check-override.outputs.skip != 'true'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.
      
      - name: Skipped (override:hygiene label present)
        if: steps.check-override.outputs.skip == 'true'
        run: echo "⚠️ Secret scanning skipped due to override:hygiene label"

  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install (immutable)
        run: yarn install --immutable
      - name: Build tokens
        run: yarn tokens:build
      - name: Debug JSON on CI
        run: |
          echo "--- package.json ---"
          cat package.json
          echo "--- packages/api/package.json ---"
          cat packages/api/package.json
      - name: Biome format (write)
        run: yarn biome format --write .
      - name: Lint
        run: yarn biome check . --files-ignore-unknown=true
      - name: Typecheck
        run: yarn typecheck

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: checks
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build tokens (generates dist/web.css)
        run: yarn tokens:build
      - name: Build API package first
        run: yarn workspace @gotmusic/api build
      - name: Build web
        run: yarn workspace @gotmusic/web build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: "1"
          # If your build touches DB at build time, point to a harmless URL
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/gotmusic_dummy
      - name: Inspect build outputs
        run: |
          echo "== ls apps/web =="
          ls -la apps/web
          echo "== ls apps/web/.next (may fail) =="
          ls -la apps/web/.next || true
          echo "== ls apps/web/out (if export) =="
          ls -la apps/web/out || true
      - name: Assert build folder exists
        run: |
          if [ -d "apps/web/.next" ] || [ -d "apps/web/out" ]; then
            echo "Build output present."
          else
            echo "::error::No Next.js build output (.next or out) found. Check the build logs above."
            exit 1
          fi
      - name: Copy .next to non-ignored location
        run: cp -r apps/web/.next web-build-output
      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web-build-output
          if-no-files-found: error
          retention-days: 7

  storybook:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: checks
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build tokens (generates dist/web.css)
        run: yarn tokens:build
      - name: Build Storybook
        run: yarn workspace @gotmusic/web storybook:build
      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: apps/web/storybook-static
          if-no-files-found: error
          retention-days: 7

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: build
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gotmusic_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Build workspace dependencies (API, tokens) so Next can resolve them
      - name: Build tokens
        run: yarn tokens:build
      - name: Build API package
        run: yarn workspace @gotmusic/api build

      # Download the build and place it back into apps/web/.next
      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: apps/web/.next

      - name: Prepare DB schema + seed
        working-directory: apps/web
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gotmusic_test
        run: |
          yarn db:push || true
          yarn db:seed || true
      - name: Run Playwright (Playwright starts/stops Next)
        working-directory: apps/web
        env:
          PW_PORT: "4123"                          # make sure playwright.config uses this
          NODE_ENV: "test"
          NEXT_TELEMETRY_DISABLED: "1"
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gotmusic_test
          E2E_AUTH_BYPASS: "1"
          GM_STORAGE_MODE: "stub"
        run: yarn test:e2e --reporter=html
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          retention-days: 7
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: apps/web/test-results
          retention-days: 7