name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack & pin Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
      - name: Install (immutable)
        run: yarn install --immutable
      - name: Lint
        run: yarn biome check . --files-ignore-unknown=true
      - name: Typecheck
        run: yarn typecheck