name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}-e2e
  cancel-in-progress: false  # Don't cancel long E2E runs

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check for override label
        if: github.event_name == 'pull_request'
        id: check-override
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const hasOverride = labels.includes('override:hygiene');
            console.log('PR labels:', labels);
            console.log('Has override:hygiene:', hasOverride);
            core.setOutput('skip', hasOverride ? 'true' : 'false');
      
      - name: Checkout code
        if: steps.check-override.outputs.skip != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for gitleaks to scan all commits
      
      - name: Run Gitleaks
        if: steps.check-override.outputs.skip != 'true'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.
      
      - name: Skipped (override:hygiene label present)
        if: steps.check-override.outputs.skip == 'true'
        run: echo "⚠️ Secret scanning skipped due to override:hygiene label"
      
      - name: Report security findings
        if: steps.check-override.outputs.skip != 'true'
        run: |
          echo "✅ Secret scanning completed successfully"
          echo "No secrets detected in codebase"

  security-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          test "$(yarn -v)" = "4.3.1"
      
      - name: Install dependencies
        run: |
          # Use corepack yarn explicitly
          corepack yarn install --immutable
      
      - name: Build tokens
        run: yarn tokens:build
      
      - name: Check for console.log in source code
        run: |
          # Use Biome to check source code for console statements
          yarn sec:console
          echo "✅ No console statements found in source code"
      
      - name: Install Gitleaks
        run: |
          # Install gitleaks for secret scanning
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/
          gitleaks version
      
      - name: Check for hardcoded secrets
        run: |
          # Use Gitleaks to check for secrets with proper allow rules
          yarn sec:secrets
          echo "✅ No hardcoded secrets found"

  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Reduced from 15 for faster feedback
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for downgrade check
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack & pin Yarn
        run: |
          # Remove system yarn to ensure corepack takes precedence
          sudo rm -f /usr/local/bin/yarn /usr/bin/yarn || true
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          # Ensure we're using the corepack yarn, not system yarn
          which yarn
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .turbo
          key: yarn-turbo-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('turbo.json') }}
          restore-keys: |
            yarn-turbo-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install (immutable)
        run: |
          # Use corepack yarn explicitly
          corepack yarn install --immutable
      - name: Check for dependency downgrades
        run: node scripts/ci/check-no-downgrades.cjs
      - name: Build tokens
        run: yarn tokens:build
      - name: Debug JSON on CI
        run: |
          echo "--- package.json ---"
          cat package.json
          echo "--- packages/api/package.json ---"
          cat packages/api/package.json
      - name: Biome format (write)
        run: yarn biome format --write .
      - name: Lint
        run: yarn biome check . --files-ignore-unknown=true
      - name: Typecheck
        run: yarn typecheck

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Reduced from 30 for faster feedback
    needs: checks
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack & pin Yarn
        run: |
          # Remove system yarn to ensure corepack takes precedence
          sudo rm -f /usr/local/bin/yarn /usr/bin/yarn || true
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          # Ensure we're using the corepack yarn, not system yarn
          which yarn
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .turbo
          key: yarn-turbo-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('turbo.json') }}
          restore-keys: |
            yarn-turbo-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build tokens (generates dist/web.css)
        run: yarn tokens:build
      - name: Build all packages with turbo
        run: yarn build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: "1"
          # If your build touches DB at build time, point to a harmless URL
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/gotmusic_dummy
      - name: Inspect build outputs
        run: |
          echo "== ls apps/web =="
          ls -la apps/web
          echo "== ls apps/web/.next (may fail) =="
          ls -la apps/web/.next || true
          echo "== ls apps/web/out (if export) =="
          ls -la apps/web/out || true
      - name: Assert build folder exists
        run: |
          if [ -d "apps/web/.next" ] || [ -d "apps/web/out" ]; then
            echo "Build output present."
          else
            echo "::error::No Next.js build output (.next or out) found. Check the build logs above."
            exit 1
          fi
      - name: Copy .next to non-ignored location
        run: cp -r apps/web/.next web-build-output
      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web-build-output
          if-no-files-found: error
          retention-days: 7

  storybook:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: checks
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack & pin Yarn
        run: |
          # Remove system yarn to ensure corepack takes precedence
          sudo rm -f /usr/local/bin/yarn /usr/bin/yarn || true
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          # Ensure we're using the corepack yarn, not system yarn
          which yarn
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .turbo
          key: yarn-turbo-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('turbo.json') }}
          restore-keys: |
            yarn-turbo-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build tokens (generates dist/web.css)
        run: yarn tokens:build
      - name: Build UI package
        run: yarn workspace @gotmusic/ui build
      - name: Build Storybook
        run: yarn workspace @gotmusic/web storybook:build
      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: apps/web/storybook-static
          if-no-files-found: error
          retention-days: 7

  e2e-public:
    name: e2e (public)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: build
    if: success()
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gotmusic_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack & pin Yarn
        run: |
          # Remove system yarn to ensure corepack takes precedence
          sudo rm -f /usr/local/bin/yarn /usr/bin/yarn || true
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          # Ensure we're using the corepack yarn, not system yarn
          which yarn
          node -v
          corepack -v
          yarn -v
      - name: Cache Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .turbo
          key: yarn-turbo-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('turbo.json') }}
          restore-keys: |
            yarn-turbo-${{ runner.os }}-
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('apps/web/package.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Verify Yarn version
        run: test "$(yarn -v)" = "4.3.1"
      - name: Install dependencies
        run: corepack yarn install --immutable
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Build workspace dependencies (API, tokens) so Next can resolve them
      - name: Build tokens
        run: yarn tokens:build
      - name: Build API package
        run: yarn workspace @gotmusic/api build

      # Download the build and place it back into apps/web/.next
      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: apps/web/.next

      - name: Prepare DB schema + seed
        working-directory: apps/web
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gotmusic_test
        run: |
          yarn db:push || true
          yarn db:seed || true
      - name: Build packages first
        run: |
          yarn workspace @gotmusic/tokens build
          yarn workspace @gotmusic/ui build
      - name: Build web (prod)
        run: yarn workspace @gotmusic/web build
      - name: Start web (prod)
        run: yarn workspace @gotmusic/web start -p 4123 &
      - name: Install wait-on
        run: yarn add -D wait-on
      - name: Wait for health
        run: npx wait-on http://127.0.0.1:4123/api/healthz -t 180000
      - name: Run Playwright (public)
        working-directory: apps/web
        env:
          PW_PORT: "4123"
          NODE_ENV: "test"
          NEXT_TELEMETRY_DISABLED: "1"
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gotmusic_test
          GM_STORAGE_MODE: "stub"
        run: yarn playwright test --reporter=html -g "@public"
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          retention-days: 7
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: apps/web/test-results
          retention-days: 7

  e2e-studio:
    name: e2e (studio/auth)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: build
    if: success()
  #   services:
  #     postgres:
  #       image: postgres:16
  #       env:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_DB: gotmusic_test
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "yarn"
  #     - name: Setup Yarn
  #       run: |
  #         corepack enable
  #         corepack prepare yarn@4.3.1 --activate
  #     - name: Install dependencies
  #       run: corepack yarn install --immutable
  #     - name: Setup database
  #       env:
  #         DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gotmusic_test
  #       run: |
  #         yarn db:push || true
  #         yarn db:seed || true
  #     - name: Build packages first
  #       run: |
  #         yarn workspace @gotmusic/tokens build
  #         yarn workspace @gotmusic/ui build
  #     - name: Build web (prod)
  #       run: yarn workspace @gotmusic/web build
  #     - name: Start web (prod)
  #       run: yarn workspace @gotmusic/web start -p 4123 &
  #     - name: Install wait-on
  #       run: yarn add -D wait-on
  #     - name: Wait for health
  #       run: npx wait-on http://127.0.0.1:4123/api/healthz -t 180000
  #     - name: Run Playwright (studio/auth)
  #       working-directory: apps/web
  #       env:
  #         PW_PORT: "4123"
  #         NODE_ENV: "test"
  #         NEXT_TELEMETRY_DISABLED: "1"
  #         DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gotmusic_test
  #         # Turn OFF the bypass to surface the real problem
  #         E2E_AUTH_BYPASS: ""
  #         GM_STORAGE_MODE: "stub"
  #       run: yarn playwright test --reporter=html -g "@studio|@auth"
  #     - name: Upload Playwright report
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: playwright-report-studio
  #         path: apps/web/playwright-report
  #         retention-days: 7