name: Issue Hygiene
on:
  issues:
    types: [opened, edited, labeled, unlabeled]
permissions:
  issues: write
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate label categories
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.issue.labels.map(l => l.name);
            
            // Escape hatch: maintainers can bypass with override:hygiene label
            if (labels.includes('override:hygiene')) {
              console.log('✅ override:hygiene label present, skipping validation');
              return;
            }
            
            const requiredCats = ['type:', 'area:', 'priority:', 'size:'];
            const missing = requiredCats.filter(cat => !labels.some(l => l.startsWith(cat)));
            
            if (missing.length) {
              const msg = `Missing required label categories: ${missing.join(', ')}`;
              core.setFailed(msg);
              await github.rest.issues.createComment({
                ...context.repo, issue_number: context.issue.number,
                body: `⚠️ ${msg}\n\nPlease add labels like: \`type:feature\`, \`area:admin\`, \`priority:P1\`, \`size:S\`.\n\n_Maintainers: add \`override:hygiene\` label to bypass this check._`
              });
            }

