name: Issue Auto-Assign
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issue to creator
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.issue.user.login]
            });

