name: sync-checklist

on:
  # Run after CI finishes on main (covers merge/squash/fast-forward)
  workflow_run:
    workflows: ["ci"]          # <-- must match your CI workflow's `name:` exactly
    types: [completed]
    branches: [main]

  # Manual button in case you want to force a run
  workflow_dispatch:

permissions:
  contents: write              # Needed to commit EXECUTION-CHECKLIST.md
  pull-requests: read
  actions: read

concurrency:
  group: sync-checklist-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with write perms)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # Fine here because we commit to the same repo

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (no lockfile changes)
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          yarn install --immutable

      - name: Run sync script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/sync-execution-checklist.mjs

      - name: Commit changes if any
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- docs.d/EXECUTION-CHECKLIST.md; then
            git add docs.d/EXECUTION-CHECKLIST.md
            git commit -m "docs(sync): update EXECUTION-CHECKLIST.md [skip ci]"
            git push
          else
            echo "No changes to EXECUTION-CHECKLIST.md"
          fi
